### ISSUE TITLE
Cannot download/enable TimeTracker 0.0.30 in NC16.0.3 

### ISSUE THREAD

**Issue by ovpc** [mtierltd/timetracker#13]
![TimeTrackerErrorScreenshot2019-08-07_12-30-19](https://user-images.githubusercontent.com/8775469/62616344-88a9fb00-b90f-11e9-91b5-ad3a2fd2ab8c.png)

When trying to download and enable get following error:

>cURL error 35: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Error.log at https://pastebin.com/Q5DjVJDy

**Comment by reinerj** [comment]
There should be a version .031 out. We checking why it is not available

**Comment by reinerj** [comment]
Please try again, there was a new release published 0.31

**Comment by ovpc** [comment]
Thanks for your efforts, I like this tool!
Got update to .31 in 16.0.3 under Stretch/Php7.2
But strangely, not in 16.0.3 under Buster/Php7.3, where I initially got the error, it is no longer available.

**Comment by reinerj** [comment]
Looks like this is out of our control. We publish it only to the App Store from Nextcloud. Maybe there is a delay until it is also available there.

**Comment by ovpc** [comment]
.31 available again now in NC16.0.3 under Buster/Php7.3 
but same error when downloading:
cURL error 35: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by reinerj** [comment]
This is not related to the time tracker package. This is a error related to the OS/libcurl to pull the package from the NC app store. You should get the same error when you try to install another package

> The URL you passed to libcurl used a protocol that this libcurl does not support. The support might be a compile-time option that you didn't use, it can be a misspelled protocol string or just a protocol libcurl has no code for.

**Comment by ovpc** [comment]
Thank you. I will ask @nachoparker to have look.
To verify, I just downloaded and enabled  Markdown Editor 2.0.6, but get no error.

**Comment by paulcalabro** [comment]
I'm getting the same error with v0.0.34.

**Comment by paulcalabro** [comment]
I'm using NC v17. The exact error message is:

```
An error occured during the request. Unable to proceed.
cURL error 35: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by ovpc** [comment]
Getting error whem updating from 0.0.34 to 0.0.38
An error occured during the request. Unable to proceed.
Couldn't update app.
Downloaded  0.0.38 and unpacked manually to inspect;
 /var/www/nextcloud/apps/timetracker/appinfo/info.xml
contains
<version>0.0.34</version>

**Comment by ovpc** [comment]
Still not found fix for this, have to manually install or update to TimeTracker 0.0.39
https://pastebin.com/p28hfyua
All other apps do update automatically, through nc-update-nc-apps-auto, TimeTracker is only app that does not?!

**Comment by nachoparker** [comment]
Seems that this app is using an old and insecure version of TLS so it is rejected by Buster libcurl

```
$ curl --verbose https://mail.nerd.hu/timetracker.tar.gz

* TCP_NODELAY set
* Expire in 149998 ms for 3 (transfer 0x538880)
* Expire in 200 ms for 4 (transfer 0x538880)
* Connected to mail.nerd.hu (84.2.34.134) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS alert, protocol version (582):
* error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
* Closing connection 0
curl: (35) error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol

```

https://www.redmine.org/issues/31755

**Comment by nachoparker** [comment]
Sounds to me that this should be fixed in the timetracker hosting

**Comment by reinerj** [comment]
We just moving the package to a new location. The current server is OpenBSD latest release. Not sure why some OS have problems to download. Will be fixed until tomorrow latest. 

When you still see problems then let us know. 

Thank you

**Comment by ovpc** [comment]
Thank you, can confirm; updates and install working again in Buster.
