### ISSUE TITLE
Counter does not start (time tracker 0.0.24 / Nextcloud 15.0.7) - Error Message popup

### ISSUE THREAD

**Issue by revil-O** [mtierltd/timetracker#6]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/3357909/58182660-509b0080-7cae-11e9-82bf-83d02b477b3a.png">

same error message in following browsers (latest versions)
- Safari
- Firefox
- Google Chrome

open time tracker and the first message without doing anything ist the following 
Error Message: ..error getting work items ... 

:path: /index.php/apps/timetracker/ajax/work-intervals
Failed to load resource: the server responded with a status of 500 ()

**Comment by puthre** [comment]
Can you see what are the exact details of the 500 error? 
Also, how was the app installed?

**Comment by revil-O** [comment]
app is installed through nextcloud. nextcloud runs on a native apache Webserver.

i'm sorry but there are no more details about this error. debugging shows nothing more than error 500()

regards revil-O

**Comment by AndreVolksdorf** [comment]
I get the same error, but found some logs.

##############################
[PHP] Error: Undefined variable: offset at /var/www/html/custom_apps/timetracker/lib/Db/WorkIntervalMapper.php#69

POST /apps/timetracker/ajax/stop-timer/Test
from 95.90.207.233 by my_username at 2019-05-27T11:50:27+00:00

##############################

[index] Error: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM `oc_timetracker_work_interval` where user_uid = ? and 
                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and 
                start < unix_timestamp(curdate() + interval 1 day - interval ? day) 
                order by id desc LIMIT 100 OFFSET 0' with params ["my_username", 7, 0]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_timetracker_work_interval' doesn't exist at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 184
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... t", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 158
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... t")
 2. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 178
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "SELECT * FROM ` ... 0", {1: "volksdorf",2: 7,3: 0})
 3. /var/www/html/lib/public/AppFramework/Db/Mapper.php line 256
    Doctrine\DBAL\Statement->execute()
 4. /var/www/html/lib/public/AppFramework/Db/Mapper.php line 344
    OCP\AppFramework\Db\Mapper->execute("SELECT * FROM ` ... c", ["my_username",7,0], 100, 0)
 5. /var/www/html/custom_apps/timetracker/lib/Db/WorkIntervalMapper.php line 64
    OCP\AppFramework\Db\Mapper->findEntities("SELECT * FROM ` ... c", ["my_username",7,0], 100, 0)
 6. /var/www/html/custom_apps/timetracker/lib/Controller/AjaxController.php line 70
    OCA\TimeTracker\Db\WorkIntervalMapper->findLatestDays("my_username", 7, 0)
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\TimeTracker\Controller\AjaxController->workIntervals()
 8. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\TimeTracker\ ... {}, "workIntervals")
 9. /var/www/html/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\TimeTracker\ ... {}, "workIntervals")
10. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\TimeTracke ... r", "workIntervals", OC\AppFramework\ ... {}, {_route: "timetr ... "})
11. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "timetr ... "})
12. /var/www/html/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "timetr ... "})
13. /var/www/html/lib/base.php line 975
    OC\Route\Router->match("/apps/timetracker/ajax/work-intervals")
14. /var/www/html/index.php line 42
    OC::handleRequest()

GET /apps/timetracker/ajax/work-intervals
from 95.90.207.233 by my_username at 2019-05-27T11:50:27+00:00

#######################
[PHP] Error: settype(): Invalid type at /var/www/html/lib/public/AppFramework/Db/Entity.php#110

GET /apps/timetracker/ajax/projects-table
from 95.90.207.233 by my_username at 2019-05-27T11:50:31+00:00

**Comment by AndreVolksdorf** [comment]
I found the problem. In the ReportItemMapper and WorkIntervalMapper is the *PREFIX* variable missing. Instead there is 'oc_' hardcoded.

**Comment by reinerj** [comment]
Thank you for the help! For some reasons we was unable to reproduce this bug. We will apply a fix asap.

**Comment by reinerj** [comment]
Fixed in 0.0.26

**Comment by jaywink** [comment]
Just updated to 0.0.26 and still seeing this issue, Nextcloud 16.0.1.

Error in logs indicates something to do with PostgreSQL? My PostgreSQL version is 10.9.

```
{"reqId":"KBl4Z7mZVTNIYah1vGja","level":3,"time":"2019-07-01T13:50:24+00:00","remoteAddr":"1.2.3.4","user":"username","app":"index","method":"GET","url":"\/index.php\/apps\/timetracker\/ajax\/work-intervals","message":{"Exception":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","Message":"An exception occurred while executing 'SELECT * FROM \"oc_timetracker_work_interval\" where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc LIMIT 100 OFFSET 0' with params [\"username\", 7, 0]:\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n                                                             ^","Code":0,"Trace":[{"file":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":184,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","type":"->","args":["An exception occurred while executing 'SELECT * FROM \"oc_timetracker_work_interval\" where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc LIMIT 100 OFFSET 0' with params [\"username\", 7, 0]:\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n                                                             ^",{"errorInfo":["42601",7,"ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n                                                             ^"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":158,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver"},{"errorInfo":["42601",7,"ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n                                                             ^"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'SELECT * FROM \"oc_timetracker_work_interval\" where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc LIMIT 100 OFFSET 0' with params [\"username\", 7, 0]:\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n                                                             ^"]},{"file":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php","line":178,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver"},{"errorInfo":["42601",7,"ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n                                                             ^"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"SELECT * FROM \"oc_timetracker_work_interval\" where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc LIMIT 100 OFFSET 0",{"1":"username","2":7,"3":0}]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":256,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":344,"function":"execute","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*timetracker_work_interval` where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc",["username",7,0],100,0]},{"file":"\/home\/nextcloud\/nextcloud\/apps\/timetracker\/lib\/Db\/WorkIntervalMapper.php","line":64,"function":"findEntities","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*timetracker_work_interval` where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc",["username",7,0],100,0]},{"file":"\/home\/nextcloud\/nextcloud\/apps\/timetracker\/lib\/Controller\/AjaxController.php","line":70,"function":"findLatestDays","class":"OCA\\TimeTracker\\Db\\WorkIntervalMapper","type":"->","args":["username",7,0]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"workIntervals","class":"OCA\\TimeTracker\\Controller\\AjaxController","type":"->","args":[]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\TimeTracker\\Controller\\AjaxController"},"workIntervals"]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\TimeTracker\\Controller\\AjaxController"},"workIntervals"]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\TimeTracker\\Controller\\AjaxController","workIntervals",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"timetracker.ajax.work_intervals"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"timetracker.ajax.work_intervals"}]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"timetracker.ajax.work_intervals"}]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/timetracker\/ajax\/work-intervals"]},{"file":"\/home\/nextcloud\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractPostgreSQLDriver.php","Line":74,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n                                                             ^","Code":"42601","Trace":[{"file":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php","line":169,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[null]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":256,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":344,"function":"execute","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*timetracker_work_interval` where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc",["username",7,0],100,0]},{"file":"\/home\/nextcloud\/nextcloud\/apps\/timetracker\/lib\/Db\/WorkIntervalMapper.php","line":64,"function":"findEntities","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*timetracker_work_interval` where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc",["username",7,0],100,0]},{"file":"\/home\/nextcloud\/nextcloud\/apps\/timetracker\/lib\/Controller\/AjaxController.php","line":70,"function":"findLatestDays","class":"OCA\\TimeTracker\\Db\\WorkIntervalMapper","type":"->","args":["username",7,0]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"workIntervals","class":"OCA\\TimeTracker\\Controller\\AjaxController","type":"->","args":[]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\TimeTracker\\Controller\\AjaxController"},"workIntervals"]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\TimeTracker\\Controller\\AjaxController"},"workIntervals"]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\TimeTracker\\Controller\\AjaxController","workIntervals",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"timetracker.ajax.work_intervals"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"timetracker.ajax.work_intervals"}]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"timetracker.ajax.work_intervals"}]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/timetracker\/ajax\/work-intervals"]},{"file":"\/home\/nextcloud\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":143,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n                                                             ^","Code":"42601","Trace":[{"file":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","line":141,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php","line":169,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[null]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":256,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":344,"function":"execute","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*timetracker_work_interval` where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc",["username",7,0],100,0]},{"file":"\/home\/nextcloud\/nextcloud\/apps\/timetracker\/lib\/Db\/WorkIntervalMapper.php","line":64,"function":"findEntities","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*timetracker_work_interval` where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc",["username",7,0],100,0]},{"file":"\/home\/nextcloud\/nextcloud\/apps\/timetracker\/lib\/Controller\/AjaxController.php","line":70,"function":"findLatestDays","class":"OCA\\TimeTracker\\Db\\WorkIntervalMapper","type":"->","args":["username",7,0]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"workIntervals","class":"OCA\\TimeTracker\\Controller\\AjaxController","type":"->","args":[]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\TimeTracker\\Controller\\AjaxController"},"workIntervals"]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\TimeTracker\\Controller\\AjaxController"},"workIntervals"]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\TimeTracker\\Controller\\AjaxController","workIntervals",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"timetracker.ajax.work_intervals"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"timetracker.ajax.work_intervals"}]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"timetracker.ajax.work_intervals"}]},{"file":"\/home\/nextcloud\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/timetracker\/ajax\/work-intervals"]},{"file":"\/home\/nextcloud\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/home\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":141}},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.1.1"}
```

**Comment by cryptoquick** [comment]
I'm also seeing this issue. Definitely something to do with timetracker and postgres.

Issue seems related to a GET for `/apps/timetracker/ajax/work-intervals`:

```
"Exception": "Doctrine\\DBAL\\Exception\\SyntaxErrorException",
    "Message": "An exception occurred while executing 'SELECT * FROM \"oc_timetracker_work_interval\" where user_uid = ? and \n                start > unix_timestamp(curdate() + interval 1 day - interval ? day) and \n                start < unix_timestamp(curdate() + interval 1 day - interval ? day) \n                order by id desc LIMIT 100 OFFSET 0' with params [\"admin\", 7, 0]:\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"1\"\nLINE 2: ...      start > unix_timestamp(curdate() + interval 1 day - in...\n
```

**Comment by reinerj** [comment]
We are looking at it and we hope to get it fixed asap

**Comment by reinerj** [comment]
We will push a new release which should fix PostgreSQL

**Comment by jaywink** [comment]
Thank you! Works perfectly now <3

**Comment by ovpc** [comment]
Hi
FYI Noticed similar repeating errors in nextcloud.log whenever loading timetracker
> [PHP] Error: settype(): Invalid type at /var/www/nextcloud/lib/public/AppFramework/Db/Entity.php#110
GET /index.php/apps/timetracker/ajax/work-intervals
from IP by user at 2020-01-12T10:50:46+00:00

It does not affect the interface, it works fine.
(NC17.0.2 on Buster Mariadb Apache Php7.3 Redis)
