### ISSUE TITLE
Security check complains about missing files after last update

### ISSUE THREAD

**Issue by elpraga** [mtierltd/timetracker#86]
The overall security check complains about missing file:

```
Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes
```

app version 0.0.50

**Comment by dhelonious** [comment]
I also could not update due to this issue. Then I tried installing time tracker from scratch, but this does not work either...

**Comment by elpraga** [comment]
I can't update from 0.0.50 to 0.0.51 using the updater. I don't dare trying to uninstall and manually install again as I'm afraid if lose my data.

**Comment by dhelonious** [comment]
For me, no data loss occured, as it is stored in the Nextcloud database, independently of the app. However, I also exported my data beforehand. If this involves too much work, I would wait for the issue to be resolved.

**Comment by domchrgit** [comment]
I have the same error after the security check event if I have the last available version (0.0.51) ...
And since from the version 0.0.48 I have already problem to update the app automatically from nextcloud ... I need to do it manually each time :(
Any advice ?

**Comment by elpraga** [comment]
Fixed in 0.0,51

**Comment by domchrgit** [comment]
Sorry but I'm under version 0.0.51 and the update to 0.0.52 does't work once again (my Nextcloud version is 20.0.6)

```
Update for timetracker to version 0.0.52 is available.
1 update available
timetracker new version available: 0.0.52
timetracker couldn't be updated
```
I still have the same error in the security check ...

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes

Raw output
==========
Array
(
    [timetracker] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/phpunit/php-file-iterator/.gitattributes] => Array
                        (
                            [expected] => 66ca641a348a43ff13dc52eb690674319332d7eef2fc3dd03a3e1dad66c6375a2c6146e964591dd557d880cf89bedb10c4dd188b43582de7e96108028a541f54
                            [current] => 
                        )

                )

        )

)
```

**Comment by dhelonious** [comment]
@domchrgit The issue also occurred for me, so I again had to update manually. Though, this is a general problem, as #90 shows.
